import type { Product, JobPost, BlogPost, TeamMember, TimelineItem } from '../types';

export const COMPANY = {
  name: 'ILKKA Healthcare Private Limited',
  shortName: 'ILKKA',
  tagline: 'Innovating for a Healthier Tomorrow',
  founded: 2019,
  headquarters: 'Bangalore, Karnataka',
  email: 'ilkkahealthcare@gmail.com',
  phone: '9900092549',
  website: 'www.ilkkahealthcare.com',
  address:
    'Jashoda Complex, Survey No. 130/2, Near McDonald\'s, Country Club, Sathnur Village, Baglur Main Road, Bangalore — 562149, Karnataka',
};

export const PORTFOLIO_AREAS = [
  {
    id: 'gynaecology',
    title: 'Gynaecology',
    description:
      'Maternal health, pregnancy support, PCOS, anaemia, calcium & vitamin D — tablets, capsules, syrups, sachets, and injectables.',
    forms: ['Tablets', 'Capsules', 'Syrups', 'Sachets'],
    color: '#e8d5e8',
  },
  {
    id: 'infertility',
    title: 'Infertility',
    description:
      'Male & female fertility, ART support, ovulation induction, and oocyte quality — science-backed formulations for better outcomes.',
    forms: ['Tablets', 'Capsules', 'Sachets'],
    color: '#d5e8da',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'foll9',
    name: 'FOLL 9™',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Tablet',
    description: 'Active solution for recurrent early pregnancy loss — prevents NTD, REPL & congenital abnormalities in the 1st trimester.',
    composition: 'L-Methylfolate 1 mg + Methylcobalamin 1500 mcg + Pyridoxal-5-Phosphate 0.5 mg',
    indication: '1st trimester — NTD, REPL, congenital abnormalities',
    color: '#fde8ef',
    image: '/products/Ilkka products/FOLL 9.png',
    nameImage: '/products/p_name/foll9.png',
  },
  {
    id: 'foll9d',
    name: 'FOLL 9-D™',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Capsule',
    description: 'Fortified with DHA & Vitamin D3 — helps prevent IUGR, pre-eclampsia & pre-term birth from 2nd trimester through lactation.',
    composition: 'LMF 1 mg + Methylcobalamin 1500 mcg + P5P 0.5 mg + DHA (40%) 200 mg + Vitamin D3 2000 IU',
    indication: '2nd trimester to lactation — IUGR, pre-eclampsia, pre-term birth',
    color: '#e8eef8',
    image: '/products/Ilkka products/FOLL 9D.png',
    nameImage: '/products/p_name/foll9D.png',
  },
  {
    id: 'foll9nv',
    name: 'FOLL9 NV™',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Tablet',
    description: 'Superior combination for complete relief from morning sickness with folic acid supplementation.',
    composition: 'Doxylamine Succinate 20 mg + Pyridoxine 20 mg + Folic Acid 5 mg',
    indication: 'Nausea & vomiting in pregnancy',
    color: '#e0f0fc',
    image: '/products/Ilkka products/FOLL 9 NV.png',
    nameImage: '/products/p_name/foll9NV.png',
  },
  {
    id: 'ilcageston10',
    name: 'ILCAGESTON™ 10',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Tablet',
    description: 'High-quality dydrogesterone formulation for dependable absorption in luteal support & threatened pregnancy loss.',
    composition: 'Dydrogesterone Tablets IP 10 mg',
    indication: 'Luteal support, threatened pregnancy loss, habitual miscarriage',
    color: '#fce8f3',
    image: '/products/catalog/product_10.jpeg',
    nameImage: '/products/p_name/ilcageston10.png',
  },
  {
    id: 'ilcagest-sr',
    name: 'ilcagest-SR',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Tablet',
    description: 'Natural micronised progesterone sustained release — spreading the eternal bliss of motherhood.',
    composition: 'Natural Micronised Progesterone SR 200 / 300 mg',
    indication: 'BOH, LPD, LPS in ART, DUB, secondary amenorrhea',
    color: '#e5f5e8',
    image: '/products/Ilkka products/ILCAGEST SR 200.png',
    nameImage: '/products/p_name/ilcagestSR.png',
  },

  {
    id: 'ilcagest-sr',
    name: 'ilcagest-SR',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Tablet',
    description: 'Natural micronised progesterone sustained release — spreading the eternal bliss of motherhood.',
    composition: 'Natural Micronised Progesterone SR 200 / 300 mg',
    indication: 'BOH, LPD, LPS in ART, DUB, secondary amenorrhea',
    color: '#e5f5e8',
    image: '/products/Ilkka products/ILCAGEST SR 300.png',
    nameImage: '/products/p_name/ilcagestSR.png',
  },

  {
    id: 'ilca-d3',
    name: 'ILCA-D3 60K',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Softgel',
    description: 'The sunshine vitamin in its purest form — recharging energy and restoring strength.',
    composition: 'Cholecalciferol USP 60,000 IU Softgel Capsules',
    indication: 'Vitamin D deficiency, bone health, immunity',
    color: '#fff3e6',
    image: '/products/Ilkka products/ILKA D3.png',
    nameImage: '/products/p_name/ilcaD3.png',
  },
  {
    id: 'rosso-xt',
    name: 'Rosso-XT™',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Tablet',
    description: 'For faster Hb rise in anaemia during pregnancy & lactation — excellent GI tolerability.',
    composition: 'Ferrous Ascorbate (elemental Iron 100 mg) + Folic acid 1.5 mg + Zinc 22.5 mg',
    indication: 'Anaemia in pregnancy & lactation',
    color: '#fde8e8',
    image: '/products/Ilkka products/ROSSO XT.png',
    nameImage: '/products/p_name/rossoXT.png',
  },
  {
    id: 'ilcal',
    name: 'ILCAL',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Tablet',
    description: 'Richest form of coral calcium with 78% absorbable calcium and 72 trace minerals.',
    composition: 'Coral Calcium 750 mg (eq. elemental Calcium 225 mg) + Vitamin D3 500 IU',
    indication: 'Pregnancy, lactation, low back pain, post-menopausal osteoporosis',
    color: '#fce8ec',
    image: '/products/Ilkka products/ILCAL.png',
    nameImage: '/products/p_name/ilcal.png',
  },
  {
    id: 'ilpreg',
    name: 'ILPREG',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Sachet',
    description: 'Sugar-free sachet — better for the baby within. Improves uteroplacental microcirculation & ovarian response.',
    composition: 'Micronised L-Arginine 3 gm + Proanthocyanidin 75 mg',
    indication: 'Pregnancy support, IUGR, poor ovarian responders',
    color: '#fce8f5',
    image: '/products/Ilkka products/ILPREG.png',
    nameImage: '/products/p_name/ilpregSachet.png',
  },
  {
    id: 'mayonika',
    name: 'MayOnika™',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Tablet',
    description: 'Restoring womanhood — effective management of PCOS with 40:1 Myo-Inositol + D-Chiro-Inositol.',
    composition: 'Myo-inositol 550 mg + D-chiro-inositol 13.8 mg + Berberine + Grape seed extract + Chromium + LMF + NAC + Vit D3',
    indication: 'PCOS — insulin resistance, ovulation, embryo quality',
    color: '#fde8f8',
    image: '/products/Ilkka products/MAYONIKA.png',
    nameImage: '/products/p_name/mayonika.png',
  },
  {
    id: 'mayonika-ds',
    name: 'Mayonika-DS',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Tablet',
    description: 'Double strength for better metabolic profile in PCOS — improves ovulation & pregnancy rates.',
    composition: 'Myo-Inositol 1100 mg + D-Chiro-Inositol 27.6 mg + Bioprin + NAC + Vit D3 1000 IU (and supporting actives)',
    indication: 'PCOS/PCOD, irregular menses, diabetic women improving conception',
    color: '#fff0e6',
    image: '/products/Ilkka products/MAYONIKA DS.png',
    nameImage: '/products/p_name/mayonikaDS.png',
  },
  {
    id: 'utika-ll',
    name: 'UTIKA-LL',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Capsule',
    description: 'Balancing microbiomes for better health — probiotics with lactoferrin for reproductive wellness.',
    composition: 'Lactobacillus 6 strains + Bifidobacterium + FOS 100 mg + Lactoferrin 50 mg',
    indication: 'ART outcomes, PCOS, BV, endometriosis, UTI, PID',
    color: '#f5e8f0',
    image: '/products/Ilkka products/UTIKA LL.png',
    nameImage: '/products/p_name/utikaLL.png',
  },
  {
    id: 'utika-susp',
    name: 'UTIKA Suspension',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Suspension',
    description: 'Preferred combination for recurrent UTI associated with renal calculus — sugar-free cranberry flavour.',
    composition: 'Cranberry extract 200 mg + D-Mannose 300 mg + Potassium-Magnesium Citrate 978 mg per 15 ml',
    indication: 'Recurrent UTI, renal calculus, burning micturition',
    color: '#e8f5fa',
    image: '/products/Ilkka products/UTIKA SUS.png',
    nameImage: '/products/p_name/utikaSuspension.png',
  },
  {
    id: 'utika-tab',
    name: 'UTIKA Tablet',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Tablet',
    description: 'Triple action formula in UTI — prevents painful and uncomfortable urinary tract infections.',
    composition: 'Cranberry Extract 200 mg + Hibiscus Sabdariffa 100 mg + D-Mannose 200 mg',
    indication: 'Urinary tract infection — prevention & recurrence',
    color: '#f0ebe8',
    image: '/products/Ilkka products/UTIKA TAB.png',
    nameImage: '/products/p_name/utikaTablet.png',
  },
  {
    id: 'utika-syrup',
    name: 'UTIKA Syrup',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Syrup',
    description: 'The natural uterine tonic — best preparation for uterine care & menstrual disorders.',
    composition: 'Ayurvedic uterine tonic formulation (as per label)',
    indication: 'Dysfunctional bleeding, menorrhagia, leucorrhoea, menstrual disorders',
    color: '#fff8e6',
    image: '/products/Ilkka products/UTIKA SYRUP.png',
    nameImage: '/products/p_name/utikaSyrup.png',
  },
  {
    id: 'protika',
    name: 'ILKKA Protika Powder',
    category: 'gynaecology',
    tag: 'Gynaecology',
    form: 'Powder',
    description: 'Fulfils dream of healthy baby — 27 essential nutrients with colostrum, GLA & DHA. Sugar free.',
    composition: 'High-quality protein (PDCAAS 1) + vitamins, minerals, colostrum, GLA, DHA',
    indication: 'Pregnancy & lactation nutrition',
    color: '#fde8ea',
    image: '/products/Ilkka products/PROTIKA.png',
    nameImage: '/products/p_name/protika.png',
  },
  {
    id: 'crepiter',
    name: 'Crepiter™',
    category: 'infertility',
    tag: 'Infertility',
    form: 'Tablet',
    description: 'For healthy sperm — reduced CoQ10 (ubiquinol) & astaxanthin combination for male infertility.',
    composition: 'CoQ10 200 mg + Astaxanthin 18 mg + L-Carnitine + Vitamin E + Lycopene + Zinc + Selenium + Glutathione',
    indication: 'Male infertility — sperm count, motility, morphology',
    color: '#ebe8f8',
    image: '/products/Ilkka products/CREPITER.png',
    nameImage: '/products/p_name/crepiter.png',
  },
  {
    id: 'ilcadhea',
    name: 'ilcadhea™',
    category: 'infertility',
    tag: 'Infertility',
    form: 'Capsule',
    description: 'Ideal combination for enriched ART outcomes — enhancing oocyte quality at the cellular level.',
    composition: 'DHEA 75 mg + Ubiquinol 100 mg + Piperine + LMF + B12 + P5P + Vitamin D3 600 IU (Drcaps®)',
    indication: 'DOR, POR, advanced maternal age, PCOS, recurrent IVF failure',
    color: '#ede8f5',
    image: '/products/Ilkka products/ILCADHEA.png',
    nameImage: '/products/p_name/ilcadhea.png',
  },
  {
    id: 'iltroz',
    name: 'ILTROZ',
    category: 'infertility',
    tag: 'Infertility',
    form: 'Tablet',
    description: 'Lifts the chances of ovulation safely & effectively in CC-resistant anovulatory infertility.',
    composition: 'Letrozole Tablets IP 2.5 mg',
    indication: 'Ovulation induction — PCOS, CC-resistant cases, IVF protocols',
    color: '#e8f0fa',
    image: '/products/Ilkka products/ILTROZ.png',
    nameImage: '/products/p_name/iltroz.png',
  },
];

export const CATEGORIES = ['All', 'gynaecology', 'infertility'];

export const JOBS: JobPost[] = [
  { id: 'j1', title: 'Formulation Scientist — Gynaecology', department: 'R&D', location: 'Bangalore, India', type: 'Full-Time' },
  { id: 'j2', title: 'Quality Assurance Officer', department: 'Quality', location: 'Bangalore, India', type: 'Full-Time' },
  { id: 'j3', title: 'Medical Representative — Infertility', department: 'Sales', location: 'Karnataka, India', type: 'Full-Time' },
  { id: 'j4', title: 'Production Pharmacist', department: 'Manufacturing', location: 'Bangalore, India', type: 'Full-Time' },
  { id: 'j5', title: 'Regulatory Affairs Executive', department: 'Regulatory', location: 'Bangalore, India', type: 'Full-Time' },
  { id: 'j6', title: 'R&D Associate — ART Formulations', department: 'R&D', location: 'Bangalore, India', type: 'Internship' },
];

export const BLOGS: BlogPost[] = [
  { id: 'b1', title: 'Supporting Women Through Every Trimester', excerpt: 'How FOLL 9 and FOLL 9-D address nutrition across pregnancy — from NTD prevention to DHA fortification.', date: 'May 2025', category: 'Gynaecology', color: '#fde8ef' },
  { id: 'b2', title: 'Male Fertility & Healthy Sperm', excerpt: 'Crepiter combines ubiquinol and astaxanthin to support sperm count, motility, and morphology.', date: 'April 2025', category: 'Infertility', color: '#ebe8f8' },
  { id: 'b3', title: 'Managing PCOS with MayOnika', excerpt: 'Inositol, berberine, and NAC — restoring hormonal balance and ovulation in PCOS patients.', date: 'March 2025', category: 'Gynaecology', color: '#fde8f8' },
  { id: 'b4', title: 'ART Outcomes with ilcadhea', excerpt: 'Targeted mitochondrial support for improved ovarian response and embryo quality.', date: 'Feb 2025', category: 'Infertility', color: '#ede8f5' },
  { id: 'b5', title: 'WHO-GMP Quality in Every Batch', excerpt: 'Our commitment to ISO-compliant practices across tablets, capsules, syrups, and sachets.', date: 'Jan 2025', category: 'Quality', color: '#dde8d5' },
  { id: 'b6', title: 'CSR: Women\'s Health in Communities', excerpt: 'Healthcare awareness and wellness programmes reflecting our belief in a healthier nation.', date: 'Dec 2024', category: 'CSR', color: '#e8e0d5' },
];

export const TEAM: TeamMember[] = [
  { name: 'Leadership Team', role: 'Management & Strategy', color: '#d5e8da', initial: 'LT' },
  { name: 'R&D Associates', role: 'Formulation & Innovation', color: '#e8e0d5', initial: 'RD' },
  { name: 'Quality Assurance', role: 'WHO-GMP & Compliance', color: '#ddd5e8', initial: 'QA' },
  { name: 'Medical Affairs', role: 'HCP Engagement', color: '#d5dde8', initial: 'MA' },
];

export const TIMELINE: TimelineItem[] = [
  { year: '2019', title: 'Company Founded', description: 'ILKKA Healthcare Private Limited established in Bangalore with a focus on gynaecology and infertility solutions.' },
  { year: '2020', title: 'Portfolio Launch', description: 'Introduced core tablets, capsules, and syrups for the domestic Indian market.' },
  { year: '2022', title: 'Expanded Range', description: 'Added infertility-focused formulations including male fertility and ART support.' },
  { year: '2024', title: 'Associate R&D Division', description: 'Formalised research for continuous formulation improvement across therapeutic areas.' },
  { year: '2025', title: 'Pan-India Presence', description: 'Strengthened distribution and partnerships with healthcare professionals across India.' },
];

export const NAV_LINKS = [
  { label: 'Home', path: '/' },
  { label: 'About', path: '/about' },
  { label: 'Products', path: '/products' },
  { label: 'Research', path: '/research' },
  { label: 'Manufacturing', path: '/manufacturing' },
  { label: 'Careers', path: '/careers' },
  { label: 'Insights', path: '/blog' },
  { label: 'Sustainability', path: '/sustainability' },
  { label: 'Contact', path: '/contact' },
];